# Generated by Django 6.0.1 on 2026-01-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to='pages/headers/'),
        ),
    ]
